### ISSUE TITLE
Twitter Posts

### ISSUE THREAD

**Issue by gerdweb** [blthemes/DevTheme#12]
Hi,
in the side bar where the newest Twitter posts should be shown for me nothing shows at all.
Is there a setting that I am missing?

Thanks and best regards

**Comment by dimobelov** [comment]
Hi, just set correct link to your Twitter profile
![2019-11-24_11h33_50](https://user-images.githubusercontent.com/6377961/69492703-7ea40c00-0eae-11ea-9586-458f557f177c.png)

**Comment by gerdweb** [comment]
Hi,
Thanks for the quick answer.
Yes that is set.
Actually I was able to see that it is working using the iPhone with Safari (basic settings).
It seems that various protection settings over all of the browsers I tested are blocking the script.

I do not think of me as a extremly security oriented person but I fear that a lot of people will not get this feature shown.
But that seems more related to the way how Twitter is sending the data than how the tool is build here.
Thanks and best regards 
(solved and can be closed)
