### ISSUE TITLE
errors with accessing db (tabs, pages etc) in latest B3.7.1

### ISSUE THREAD

**Issue by Joduai** [blthemes/DevTheme#2]
Using devtheme along with latest bludit's method pops up errors with accessing - among the others - global tag list using _Theme::plugins('siteSidebar')_ method.
The problem is raised on bludit;s forum in this thread:
https://forum.bludit.org/viewtopic.php?f=14&t=1391&p=6375

edit: something touched me to try one additional thing
Overwrite pages.php with default theme's page, and voilla. Problems temporarily solved.
I guess I'll mess with it a bit more.

edit 2: as it goes to tags, found the reason of troubles.
Changing:

```
<?php
  $tags = $page->tags(true);
  foreach($tags as $tagKey=>$tagName) :?>

```
to
`<?php foreach($page->tags(true) as $tagKey=>$tagName) :?>`

solved the issue with showing global tags array using <?php Theme::plugins('siteSidebar') ?>

Look like assigning arrays to variables are causing troubles.

**Comment by dimobelov** [comment]
@Joduai , can you try something? Just change $tags to $ttags:
```
<?php
  $ttags = $page->tags(true);
  foreach($ttags as $tagKey=>$tagName) :?>
```
and tell me is error exist. Later this week we will have new version of DevTheme.

**Comment by Joduai** [comment]
@dimobelov 
I just bite my tongue why I didn't think that same var does already exist.
Maybe due to too many small things and errors to fix in the meantime.
I confirm that it works like a charm, and tags are being shown on subpages as supposed using _Theme::plugins('siteSidebar')_ method

**Comment by dimobelov** [comment]
@Joduai , you can test now v3.8.0 of theme. Not final release but closer. If you find something tell me, pls.

**Comment by Joduai** [comment]
@dimobelov 
At frist glance everything seems to be working, and doesn't throw any errors.
Things I'd suggest to look at:

- search doesn't consider sticky pages; I'm not sure if I'd call this a bug, as builtin' bludit's search also doesn't search through sticky pages 
- for static pages you could consider a condition that when slug contains '404' string, page should be hidden in any menu
- should "find us on" footer block contain page slogan? I've got all social networks empty? Maybe this block should be hidden when all social media links stay empty?
- if page has an uploaded logo shouldn't "{}" coloured chars in top bar be hidden?
- as it goes to logo, it has a hardcoded width="120" in <img> tag, thus it is being shown a bit flattened.
Maybe you assumed that logo img is squared by default?

**Comment by dimobelov** [comment]
@Joduai 
> * search doesn't consider sticky pages; .... **Fixed**
> * for static pages you could consider a condition that when slug contains '404' string, page should be hidden in any menu **Added check for 404**
> * should "find us on" footer block contain page slogan? I've got all social networks empty? Maybe this block should be hidden when all social media links stay empty? **Fixed partially. Some users want slogan for SEO purposes**
> * if page has an uploaded logo shouldn't "{}" coloured chars in top bar be hidden? **Fixed**
> * as it goes to logo, it has a hardcoded width="120" in  tag, thus it is being shown a bit flattened.  Maybe you assumed that logo img is squared by default? **Fixed partially. Now Bludit do not have option to limit image size for logo. I added resize by CDN to fit 120px width. Users can upload any image as logo and without limit this will broke Header design. I want to keep my inbox clean :)**

**Comment by Joduai** [comment]
@dimobelov 
fantastic, search works flawlessly! :)

For the slogan I can't imagine at once all possible usecases.
Pity is that bludit doesn't offer some kind of a theme hooks in admin panel for additional options.
Or maybe there's something I'm not aware of.

For the logo thingy I'm aware of all restrictions.
It's just that I would hit with css to make it smaller with max-height and max-width properties, as it should restrain from showing badly scaled img using encoded dimension(s) in html tag.

But as for now imo everything is ready2go.

**Comment by dimobelov** [comment]
I have to finish some small things and will release it. Thank for conversation and good tips!

**Comment by Joduai** [comment]
@dimobelov 
Ohh, yet I found a small thing with translation, and i'm not sure if it is caused by javascript.
Just translated theme's en.json to polish language.
When search page loads the translated header ($L->get('search-results-for'))  in any other language than english blinks, and is replaced with english phrase "Search results for [term]" as soon as search results pops up. It takes less than 1s after page load, so the language switch should be visible.

ps. pl trnslation in attachment
[pl_PL.zip](https://github.com/blthemes/DevTheme/files/2910684/pl_PL.zip)

**Comment by Joduai** [comment]
@dimobelov 
Could you also check if search doesn't check page titles?

**Comment by dimobelov** [comment]
Strings, that appear on search page results, are hardcoded in javascript file. You can change them in code for now.
Search work on both title and content.
Thanks for Polish language. Added.
