### ISSUE TITLE
Externalizing language

### ISSUE THREAD

**Issue by ghost** [blthemes/DevTheme#4]
All the words displayed on the interface of the theme should be in a language file so we can translate it quickly instead of looking in all the files and translate it manually.

Per example, file searchbundle.min.js contains english terms.

I can help you to translate it in french if needed.

**Comment by dimobelov** [comment]
https://github.com/blthemes/Blekathlon/issues/7

**Comment by dimobelov** [comment]
Fixed in 3.8.1
