### ISSUE TITLE
Is there a un-minified version for this theme?

### ISSUE THREAD

**Issue by detlevhfischer** [blthemes/DevTheme#8]
Hi,
I am using  devtheme as a basis for a small site for people with disabilities that will document methods they can use to test the acessibility of websites and apps. It is therefore important that the site itself and the theme used is accessible (good contrast, keyboard focus visibility, good etc.) I think devtheme is not a bad starting point but I would like to make some changes, which I am happy to make available to you should you be interested. That's why I wonder if there is an un-minified version of the CSS for this theme - it would be easier to adapt to tweak it for accessibility.
Thanks! Detlev

**Comment by dimobelov** [comment]
Hi, i uploaded unminified css https://github.com/blthemes/DevTheme/blob/unmin-css/css/bundle.css
I would be interested to see your modifications. Write as you finish.

**Comment by detlevhfischer** [comment]
Hi @dimobelov Thanks for adding the un-minified version.  After exploring bludit a bit more I have for now changed track since I realised that having user comments with replies is a main requirement - we have a CONTAO installation that supports that, so I can simply create a new starting pint and benefit from the accessibility stuff I have already put in in that instalation - but I may start using bludit for something else soon and then have a go at approving the accessibility. I'll keep you posted.

**Comment by davidzoli** [comment]
Is there any chance, we could get the source of the css and js files? 
They are "bundled", I assume they have sass/js source using part of the Bootstrap and others maybe.
I'm trying to customize this theme, but would be easier and more professional working with the sources.

Thanks!
